package com.supermarket.checkout.model;

import org.springframework.data.annotation.Id;
import org.springframework.data.relational.core.mapping.Table;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Positive;
import java.time.LocalDate;
import java.math.BigDecimal;

@Table("OFFERS")
public class Offer {

    @Id
    private Long id; // generated by database

    @NotNull
    private Long productId;

    @Positive
    private Integer requiredQuantity;

    @Positive
    private BigDecimal bundlePrice;
    
    @NotNull
    private LocalDate startDate, endDate;

    public Offer() {
    }

    public Offer(Long id, Long productId, Integer requiredQuantity, BigDecimal bundlePrice, LocalDate startDate, LocalDate endDate) {
        this.id = id;
        this.productId = productId;
        this.requiredQuantity = requiredQuantity;
        this.bundlePrice = bundlePrice;
        this.startDate = startDate;
        this.endDate = endDate;
    }

    public Long getId() {
        return id;
    }

    public Long getProductId() {
        return productId;
    }

    public Integer getRequiredQuantity() {
        return requiredQuantity;
    }

    public BigDecimal getBundlePrice() {
        return bundlePrice;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public void setProductId(Long productId) {
        this.productId = productId;
    }

    public void setRequiredQuantity(Integer requiredQuantity) {
        this.requiredQuantity = requiredQuantity;
    }

    public void setBundlePrice(BigDecimal bundlePrice) {
        this.bundlePrice = bundlePrice;
    }

    public LocalDate getStartDate() {
        return startDate;
    }

    public void setStartDate(LocalDate startDate) {
        this.startDate = startDate;
    }

    public LocalDate getEndDate() {
        return endDate;
    }

    public void setEndDate(LocalDate endDate) {
        this.endDate = endDate;
    }
}