# Server Configuration  
# Port 0 means Spring Boot will automatically choose an available port
server.port=0

# Application name (appears in logs and monitoring endpoints)
spring.application.name=Supermarket Checkout App

spring.datasource.url=jdbc:h2:file:~/springboot-checkout-db
spering.sql.init.mode=always
spring.h2-console.enabled=true

# Logging Configuration
# This shows detailed logs so you can learn what Spring Boot is doing
logging.level.org.springframework.web=DEBUG
logging.level.com.supermarket.checkout=DEBUG