# Server Configuration  
# Port 0 means Spring Boot will automatically choose an available port
server.port=8080

# Application name (appears in logs and monitoring endpoints)
spring.application.name=Supermarket Checkout App

# database configuration
spring.datasource.url=jdbc:h2:mem:checkoutdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=demo

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.sql.init.mode=always


# Logging Configuration
# This shows detailed logs so you can learn what Spring Boot is doing
logging.level.org.springframework.web=DEBUG
logging.level.com.supermarket.checkout=DEBUG